### PR TITLE
Add Actions

### PR DESCRIPTION
**Pull request by Fancy2209**
I noticed #63 only tested on windows,
this does the same as that PR but also
- Upload the Compiled build of MonaServer
- Runs on Windows, Linux, MacOS 12 (intel) and MacOS 14 (M1)

Hope it's useful!

### CODE REVIEW

**Comment by Fancy2209** [comment]
I see they are failing, I was testing on a external repo so I forgot to change some stuff
Will work on a fix asap

**Comment by Fancy2209** [comment]
Oh i see you fixed the errors, thank you!
I think M1 needs openssl from brew though, only the MacOS 12 runner has it

**Comment by thomasjammet** [comment]
Hey Fancy, thank you for your great work! 

I see that someone asked for MacOS prebuilt binaries so I wanted to try this.

Yes unfortunately debugging Github actions is not simple, I have tried 2 last changes right now, feel free to push a new PR if you find the solutions, mainly macos.

Thanks again

**Comment by Fancy2209** [comment]
> Hey Fancy, thank you for your great work!
> 
> I see that someone asked for MacOS prebuilt binaries so I wanted to try this.
> 
> Yes unfortunately debugging Github actions is not simple, I have tried 2 last changes right now, feel free to push a new PR if you find the solutions, mainly macos.
> 
> Thanks again

For now I will simply leave out M1, macOS 14 ships LibreSSL and make doesn't like it
UnitTests are hanging on windows but I hope what I did fixes it

**Pull request merged**
